# Generated by Django 5.2.9 on 2026-01-05 15:33

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seeker', '0002_remove_seeker_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(null=True, upload_to='resume')),
                ('resume_vector', pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True)),
                ('resume_text', models.TextField(blank=True, null=True)),
                ('ats_score', models.FloatField(default=0.0)),
                ('semantic_score', models.FloatField(default=0.0)),
                ('skills', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seeker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resume', to='Seeker.seeker')),
            ],
        ),
    ]
