# Generated by Django 5.2.9 on 2026-01-07 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seeker', '0004_remove_seeker_vector_seeker_image_education_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seeker',
            name='discription',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='seeker',
            name='headline',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
