# Generated by Django 5.2.10 on 2026-01-11 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seeker', '0005_seeker_discription_seeker_headline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='semantic_score',
            new_name='entity_score',
        ),
        migrations.AlterField(
            model_name='resume',
            name='resume_text',
            field=models.TextField(blank=True, default=list),
        ),
    ]
