# Generated by Django 5.2.10 on 2026-01-11 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seeker', '0006_rename_semantic_score_resume_entity_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seeker',
            name='discription',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='seeker',
            name='headline',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
