# Generated by Django 5.2.10 on 2026-01-27 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seeker', '0008_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='ats_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='application',
            name='category',
            field=models.CharField(choices=[('excellent', 'Excellent Match'), ('good', 'Good Match'), ('low', 'Low Match')], db_index=True, max_length=20, null=True),
        ),
    ]
