# Generated by Django 5.2.10 on 2026-01-11 08:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recruter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('company_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('phone', models.CharField(max_length=11)),
                ('address', models.TextField()),
                ('size', models.CharField(choices=[('1-10', '1-10 Employees'), ('11-50', '11-50 Employees'), ('51-200', '51-200 Employees'), ('200+', '200+ Employees')], max_length=20)),
                ('industry', models.CharField(help_text='Example: IT,Finance,Helthcare etc..', max_length=100)),
                ('Organization_type', models.CharField(choices=[('STARTUP', 'Startup'), ('PRIVATE', 'Private'), ('MNC', 'MNC'), ('CONSULTANCY', 'Consultancy'), ('NGO', 'NGO')], max_length=20)),
                ('approval_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('sub_status', models.CharField(choices=[('FREE', 'Free'), ('PENDING_PAYMENT', 'Pending_payment'), ('ACTIVE', 'Active'), ('EXPIRED', 'Expired')], default='FREE', max_length=20)),
                ('sub_due', models.DateField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
