# Generated by Django 5.2.10 on 2026-01-11 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0002_recruter_decription_alter_recruter_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruter',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos'),
        ),
    ]
