# Generated by Django 5.2.10 on 2026-01-15 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0003_recruter_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gst_certificate', models.FileField(blank=True, null=True, upload_to='recruter_docs/gst')),
                ('registration', models.FileField(blank=True, null=True, upload_to='recruter_docs/registration')),
                ('pan_card', models.FileField(blank=True, null=True, upload_to='recruter_docs/pan')),
                ('address_proof', models.FileField(blank=True, null=True, upload_to='recruter_docs/address_proof')),
                ('gst_verified', models.BooleanField(default=False)),
                ('registration_verified', models.BooleanField(default=False)),
                ('pan_verified', models.BooleanField(default=False)),
                ('address_proof_verified', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recruter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='recruiter.recruter')),
            ],
        ),
    ]
