# Generated by Django 5.2.10 on 2026-01-21 17:50

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0005_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_vector',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True),
        ),
    ]
