# Generated by Django 5.2.10 on 2026-02-10 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0006_job_job_vector'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.PositiveIntegerField()),
                ('job_limit', models.PositiveIntegerField()),
                ('resume_pooling', models.BooleanField(default=False)),
                ('ai_ranking', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
