# Generated by Django 5.2.10 on 2026-02-15 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0007_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='duration',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recruter',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recruiter.plan'),
        ),
    ]
