# Generated by Django 5.2.10 on 2026-02-15 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0008_plan_duration_recruter_plan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='ai_ranking',
            new_name='ai_chat',
        ),
        migrations.AlterField(
            model_name='plan',
            name='job_limit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
