# Generated by Django 5.2.10 on 2026-02-22 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0009_rename_ai_ranking_plan_ai_chat_alter_plan_job_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='job_banners'),
        ),
    ]
